title: SolarBench
description: Web page for SolarBench
theme: just-the-docs
logo: /assets/imgs/solarbench_logo_text.png

url: https://solar4cast.github.io
baseurl: /solarbench-site

exclude:
  - _local/
  - assets/data/*.nc
  - assets/data/*.zip
  - assets/data/*.tsv
