title: SolarBench
description: Web page for SolarBench
theme: just-the-docs
logo: /assets/imgs/solarbench_logo_text.png

url: https://solarbench.github.io
baseurl: ""

exclude:
  - _local/
  - assets/data/*.nc
  - assets/data/*.zip
  - assets/data/*.tsv
